app:
  baseUrl: http://localhost:7007
  listen:
    port: 7007

backend:
  baseUrl: http://localhost:7007
  listen: :7007
  database:
    client: pg
    connection: 'postgresql://postgres:secret@postgres:5432'

techdocs:
  builder: local
  generator:
    runIn: local
  publisher:
    type: local

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Domain, Group, User]
