services:
  backstage:
    image: backstage
    build: .
    env_file:
      - docker.env
    ports:
      - 7007:7007
    volumes:
      - ./app-config.yaml:/app/app-config.yaml
      - ./catalogs:/catalogs
      - ./data/techdocs:/data/techdocs
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
