version: '3'
services:
  backstage:
    depends_on: [ postgres ]
    image: backstage
    build: .
    env_file:
      - docker.env
    ports:
      - 7007:7007
    volumes:
      - ./app-config.yaml:/app/app-config.yaml
      - ./catalogs:/catalogs
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
