---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dx2devops-backstage-containerapp
  title: Backstage on Azure Container Apps
  description: |
    Enterprise Backstage DevOps on Azure Container Apps
  tags:
    - backstage
    - devops
    - azure-container-apps
    - azure-developer-cli
  links:
    - title: GitHub Repository
      url: https://github.com/yaegashi/dx2devops-backstage-containerapp
  annotations:
    github.com/project-slug: yaegashi/dx2devops-backstage-containerapps
spec:
  type: library
  owner: team-a
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dx2devops-redmine-containerapp
  title: Redmine on Azure Container Apps
  description: |
    Enterprise Redmine DevOps on Azure Container Apps
  tags:
    - redmine
    - devops
    - azure-container-apps
    - azure-developer-cli
  links:
    - title: GitHub Repository
      url: https://github.com/yaegashi/dx2devops-redmine-containerapp
  annotations:
    github.com/project-slug: yaegashi/dx2devops-redmine-containerapps
spec:
  type: library
  owner: team-b
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: org-x
  title: Org X
spec:
  type: organization
  profile:
    email: org-x@example.com
  children: [team-a, team-b]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  title: Team A
spec:
  type: team
  profile:
    email: team-a@example.com
  parent: org-x
  children: []
  members: [user1, user2]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  title: Team B
spec:
  type: team
  profile:
    email: team-b@example.com
  parent: org-x
  children: []
  members: [user3, user4]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user1
  title: User 1
spec:
  profile:
    email: user1@example.com
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user2
  title: User 2
spec:
  profile:
    email: user2@example.com
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user3
  title: User 3
spec:
  profile:
    email: user3@example.com
  memberOf: [team-b]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: user4
  title: User 4
spec:
  profile:
    email: user4@example.com
  memberOf: [team-b]
